name: "maven build"
description: "maven build...."
strategy:
  matrix:
    maven: [ '3.5.4', '3.6.3', '3.8.2' ]
    java: [ '8', '11', '16']
runs:
  using: "composite"
  steps:
    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.2.1
      with:
        java-version: 8

    - name: maven build
      run: mvn -V ...
