name: "Build dotnet application"
description: "Build dotnet..."
inputs:
  dotnet-version:
    description: 'The dotnet version to use'
    default: '2.1.x'
    required: false
  project-path:
    description: 'The path to the project'
    required: true
    

runs:
  using: "composite"
  steps: 
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
        
    - run: dotnet restore ${{ inputs.project-path }}
      shell: bash

    - name: Building dotnet application
      run: dotnet build ${{ inputs.project-path }} 
      shell: bash
    - name: Echo dotnet application
      run: echo "hi I am dotnet" 
      shell: bash
 
