name: Build

on:
  workflow_call:
    inputs:
      dotnet-version:
        description: 'The dotnet version to use'
        default: '2.1.x'
        required: false
        type: string
      project-path:
        description: 'The path to the project'
        required: true
        type: string
      tech-type:
        description: 'technology type'
        required: true
        type: string
jobs:
  build_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        
      - name: Build dotnet job
        if: contains('dotnet',inputs.tech-type)
        uses: ./.github/actions/dotnet-build
        with:
          dotnet-version: 5.0.x
          project-path: src/DemoReusableTemplates.csproj
#       - name: Checkout the code
#         uses: actions/checkout@v2    
#       - name: Build java job
#         if: contains('java',inputs.tech-type)
#         uses: tapasmishraarc/ReusableGitHubWorkflows/maven-build@v0.0.1
       
 
